services:
  # Backend API Service
  - type: web
    name: payroll-backend
    env: node
    plan: starter
    branch: main
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d

  # Frontend (React) as Web Service
  - type: web
    name: payroll-frontend
    env: node
    plan: starter
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    rootDir: client
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://payroll-backend.onrender.com
