services:
  # =========================
  # Backend API Service
  # =========================
  - type: web
    name: payroll-backend
    env: node
    plan: starter
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js   # 👈 change to app.js/server.js if that's your entry file
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d

  # =========================
  # Frontend React Service
  # =========================
  - type: web
    name: payroll-frontend
    env: static
    plan: starter
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://payroll-backend.onrender.com
